/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MedicineRouteImport } from './routes/medicine'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as EhrRouteImport } from './routes/ehr'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as IndexRouteImport } from './routes/index'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineRoute = MedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const EhrRoute = EhrRouteImport.update({
  id: '/ehr',
  path: '/ehr',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/credentials': typeof CredentialsRoute
  '/ehr': typeof EhrRoute
  '/explorer': typeof ExplorerRoute
  '/medicine': typeof MedicineRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/credentials': typeof CredentialsRoute
  '/ehr': typeof EhrRoute
  '/explorer': typeof ExplorerRoute
  '/medicine': typeof MedicineRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRoute
  '/credentials': typeof CredentialsRoute
  '/ehr': typeof EhrRoute
  '/explorer': typeof ExplorerRoute
  '/medicine': typeof MedicineRoute
  '/research': typeof ResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claims'
    | '/credentials'
    | '/ehr'
    | '/explorer'
    | '/medicine'
    | '/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claims'
    | '/credentials'
    | '/ehr'
    | '/explorer'
    | '/medicine'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/claims'
    | '/credentials'
    | '/ehr'
    | '/explorer'
    | '/medicine'
    | '/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimsRoute: typeof ClaimsRoute
  CredentialsRoute: typeof CredentialsRoute
  EhrRoute: typeof EhrRoute
  ExplorerRoute: typeof ExplorerRoute
  MedicineRoute: typeof MedicineRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine': {
      id: '/medicine'
      path: '/medicine'
      fullPath: '/medicine'
      preLoaderRoute: typeof MedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ehr': {
      id: '/ehr'
      path: '/ehr'
      fullPath: '/ehr'
      preLoaderRoute: typeof EhrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimsRoute: ClaimsRoute,
  CredentialsRoute: CredentialsRoute,
  EhrRoute: EhrRoute,
  ExplorerRoute: ExplorerRoute,
  MedicineRoute: MedicineRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
